# Generated by Django 5.1.2 on 2024-12-08 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=100)]),
        ),
    ]
